### ISSUE TITLE
Feature Request: Support OpenAI / Mistral compatible embedding REST interface

### ISSUE THREAD

**Issue by michaelwechner** [wyona/katie-backend#32]
There are various services, which provide OpenAI / Mistral compatible REST interfaces, like for example

https://github.com/Repositorium-ch/embedding-service

Katie should allow the configuration of such an endpoint

**Comment by michaelwechner** [comment]
https://github.com/Repositorium-ch/embedding-service/issues/6

**Comment by colin-r-carter** [comment]
@michaelwechner https://github.com/Repositorium-ch/embedding-service/issues/6 should be fixed, so this implementation should now hopefully work

**Comment by michaelwechner** [comment]
Great, thank you very much! Works now very fine :-) we will have to slightly enhance Katie, such that one can add the alternative endpoint, e.g. http://localhost:3000/v1/embeddings

**Comment by michaelwechner** [comment]
Let us try to re-use src/main/java/com/wyona/katie/handlers/OpenAIEmbeddings.java and also do this for MistralAIEmbed

**Comment by colin-r-carter** [comment]
Is it not possible to just set openai.host=https://api.openai.com to an arbitrary definable string in src/main/resources/application.properties? 

The OpenAIGenerate.java handler loads that url too, right? In that case both the generate and the embed handlers could connect to third party services following the same OpenAI format, by just passing a different url. As far as I know that would allow to switch to services like Ollama or [LiteLLM](https://github.com/BerriAI/litellm) quite easily as well, or am I missing something? 🙈

**Comment by michaelwechner** [comment]
Implemented :-)

- Go to Domain Settings
- Click on Reindex
- Select OpenAI Compatible
- Enter model (e.g. mistral-embed), endpoint (e.g. https://api.mistral.ai/v1/embeddings) and API token
